# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/authorizer/authorizer/v1/authorizer.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'protoc-gen-openapiv2/options/annotations_pb'
require 'google/protobuf/struct_pb'
require 'aserto/api/v1/policy_context_pb'
require 'aserto/api/v1/identity_context_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/authorizer/authorizer/v1/authorizer.proto", :syntax => :proto3) do
    add_message "aserto.authorizer.authorizer.v1.DecisionTreeRequest" do
      optional :policy_context, :message, 1, "aserto.api.v1.PolicyContext", json_name: "policyContext"
      optional :identity_context, :message, 2, "aserto.api.v1.IdentityContext", json_name: "identityContext"
      optional :options, :message, 3, "aserto.authorizer.authorizer.v1.DecisionTreeOptions", json_name: "options"
      optional :resource_context, :message, 4, "google.protobuf.Struct", json_name: "resourceContext"
    end
    add_message "aserto.authorizer.authorizer.v1.DecisionTreeOptions" do
      optional :path_separator, :enum, 1, "aserto.authorizer.authorizer.v1.PathSeparator", json_name: "pathSeparator"
    end
    add_message "aserto.authorizer.authorizer.v1.DecisionTreeResponse" do
      optional :path_root, :string, 1, json_name: "pathRoot"
      optional :path, :message, 3, "google.protobuf.Struct", json_name: "path"
    end
    add_message "aserto.authorizer.authorizer.v1.IsRequest" do
      optional :policy_context, :message, 1, "aserto.api.v1.PolicyContext", json_name: "policyContext"
      optional :identity_context, :message, 2, "aserto.api.v1.IdentityContext", json_name: "identityContext"
      optional :resource_context, :message, 3, "google.protobuf.Struct", json_name: "resourceContext"
    end
    add_message "aserto.authorizer.authorizer.v1.Decision" do
      optional :decision, :string, 1, json_name: "decision"
      optional :is, :bool, 2, json_name: "is"
    end
    add_message "aserto.authorizer.authorizer.v1.IsResponse" do
      repeated :decisions, :message, 1, "aserto.authorizer.authorizer.v1.Decision", json_name: "decisions"
    end
    add_message "aserto.authorizer.authorizer.v1.QueryOptions" do
      optional :metrics, :bool, 1, json_name: "metrics"
      optional :instrument, :bool, 2, json_name: "instrument"
      optional :trace, :enum, 3, "aserto.authorizer.authorizer.v1.TraceLevel", json_name: "trace"
      optional :trace_summary, :bool, 4, json_name: "traceSummary"
    end
    add_message "aserto.authorizer.authorizer.v1.QueryRequest" do
      optional :identity_context, :message, 1, "aserto.api.v1.IdentityContext", json_name: "identityContext"
      optional :query, :string, 2, json_name: "query"
      optional :input, :string, 3, json_name: "input"
      optional :options, :message, 4, "aserto.authorizer.authorizer.v1.QueryOptions", json_name: "options"
      optional :policy_context, :message, 5, "aserto.api.v1.PolicyContext", json_name: "policyContext"
      optional :resource_context, :message, 6, "google.protobuf.Struct", json_name: "resourceContext"
    end
    add_message "aserto.authorizer.authorizer.v1.QueryResponse" do
      repeated :results, :message, 1, "google.protobuf.Struct", json_name: "results"
      optional :metrics, :message, 2, "google.protobuf.Struct", json_name: "metrics"
      repeated :trace, :message, 3, "google.protobuf.Struct", json_name: "trace"
      repeated :trace_summary, :string, 4, json_name: "traceSummary"
    end
    add_enum "aserto.authorizer.authorizer.v1.PathSeparator" do
      value :PATH_SEPARATOR_UNKNOWN, 0
      value :PATH_SEPARATOR_DOT, 1
      value :PATH_SEPARATOR_SLASH, 2
    end
    add_enum "aserto.authorizer.authorizer.v1.TraceLevel" do
      value :TRACE_LEVEL_UNKNOWN, 0
      value :TRACE_LEVEL_OFF, 1
      value :TRACE_LEVEL_FULL, 2
      value :TRACE_LEVEL_NOTES, 3
      value :TRACE_LEVEL_FAILS, 4
    end
  end
end

module Aserto
  module Authorizer
    module Authorizer
      module V1
        DecisionTreeRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.DecisionTreeRequest").msgclass
        DecisionTreeOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.DecisionTreeOptions").msgclass
        DecisionTreeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.DecisionTreeResponse").msgclass
        IsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.IsRequest").msgclass
        Decision = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.Decision").msgclass
        IsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.IsResponse").msgclass
        QueryOptions = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.QueryOptions").msgclass
        QueryRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.QueryRequest").msgclass
        QueryResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.QueryResponse").msgclass
        PathSeparator = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.PathSeparator").enummodule
        TraceLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.authorizer.authorizer.v1.TraceLevel").enummodule
      end
    end
  end
end
