# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: aserto/authorizer/authorizer/v1/authorizer.proto for package 'aserto.authorizer.authorizer.v1'

require 'grpc'
require 'aserto/authorizer/authorizer/v1/authorizer_pb'

module Aserto
  module Authorizer
    module Authorizer
      module V1
        module Authorizer
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'aserto.authorizer.authorizer.v1.Authorizer'

            rpc :DecisionTree, ::Aserto::Authorizer::Authorizer::V1::DecisionTreeRequest, ::Aserto::Authorizer::Authorizer::V1::DecisionTreeResponse
            rpc :Is, ::Aserto::Authorizer::Authorizer::V1::IsRequest, ::Aserto::Authorizer::Authorizer::V1::IsResponse
            rpc :Query, ::Aserto::Authorizer::Authorizer::V1::QueryRequest, ::Aserto::Authorizer::Authorizer::V1::QueryResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
