# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/options/v1/ids.proto

require 'google/protobuf'

require 'google/protobuf/descriptor_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/options/v1/ids.proto", :syntax => :proto3) do
    add_enum "aserto.options.v1.IDType" do
      value :ID_TYPE_UNKNOWN, 0
      value :ID_TYPE_ACCOUNT, 1
      value :ID_TYPE_TENANT, 2
      value :ID_TYPE_ERROR, 3
      value :ID_TYPE_POLICY, 4
      value :ID_TYPE_REQUEST, 5
      value :ID_TYPE_PROVIDER, 6
      value :ID_TYPE_CONNECTION, 7
      value :ID_TYPE_INVITE, 8
      value :ID_TYPE_POLICY_BUILDER, 9
      value :ID_TYPE_POLICY_REPO, 10
    end
  end
end

module Aserto
  module Options
    module V1
      IDType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.options.v1.IDType").enummodule
    end
  end
end
