# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/account.proto

require 'google/protobuf'

require 'aserto/api/v1/tenant_pb'
require 'aserto/options/v1/ids_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/account.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.Account" do
      optional :id, :string, 1, json_name: "id"
      repeated :tenants, :message, 2, "aserto.api.v1.Tenant", json_name: "tenants"
      optional :default_tenant, :string, 3, json_name: "defaultTenant"
      optional :registration_date, :int64, 4, json_name: "registrationDate"
      optional :personal_tenant, :message, 5, "aserto.api.v1.Tenant", json_name: "personalTenant"
    end
  end
end

module Aserto
  module Api
    module V1
      Account = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.Account").msgclass
    end
  end
end
