# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/change.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/change.proto", :syntax => :proto3) do
    add_enum "aserto.api.v1.ChangeType" do
      value :CHANGE_TYPE_UNKNOWN, 0
      value :CHANGE_TYPE_CREATED, 1
      value :CHANGE_TYPE_UPDATED, 2
      value :CHANGE_TYPE_DELETED, 3
    end
  end
end

module Aserto
  module Api
    module V1
      ChangeType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.ChangeType").enummodule
    end
  end
end
