# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/identity_context.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/identity_context.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.IdentityContext" do
      optional :identity, :string, 2, json_name: "identity"
      optional :type, :enum, 3, "aserto.api.v1.IdentityType", json_name: "type"
    end
    add_enum "aserto.api.v1.IdentityType" do
      value :IDENTITY_TYPE_UNKNOWN, 0
      value :IDENTITY_TYPE_NONE, 1
      value :IDENTITY_TYPE_SUB, 2
      value :IDENTITY_TYPE_JWT, 3
    end
  end
end

module Aserto
  module Api
    module V1
      IdentityContext = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.IdentityContext").msgclass
      IdentityType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.IdentityType").enummodule
    end
  end
end
