# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/log.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/log.proto", :syntax => :proto3) do
    add_enum "aserto.api.v1.LogLevel" do
      value :LOG_LEVEL_UNKNOWN, 0
      value :LOG_LEVEL_TRACE, 1
      value :LOG_LEVEL_DEBUG, 2
      value :LOG_LEVEL_INFO, 3
      value :LOG_LEVEL_WARN, 4
      value :LOG_LEVEL_ERROR, 5
      value :LOG_LEVEL_FATAL, 6
      value :LOG_LEVEL_PANIC, 7
    end
  end
end

module Aserto
  module Api
    module V1
      LogLevel = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.LogLevel").enummodule
    end
  end
end
