# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/metadata.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/metadata.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.Metadata" do
      optional :created_at, :message, 1, "google.protobuf.Timestamp", json_name: "createdAt"
      optional :updated_at, :message, 2, "google.protobuf.Timestamp", json_name: "updatedAt"
      optional :deleted_at, :message, 3, "google.protobuf.Timestamp", json_name: "deletedAt"
      proto3_optional :connection_id, :string, 4, json_name: "connectionId"
      proto3_optional :hash, :string, 5, json_name: "hash"
    end
  end
end

module Aserto
  module Api
    module V1
      Metadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.Metadata").msgclass
    end
  end
end
