# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/name_availability.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/name_availability.proto", :syntax => :proto3) do
    add_enum "aserto.api.v1.NameAvailability" do
      value :NAME_AVAILABILITY_UNKNOWN, 0
      value :NAME_AVAILABILITY_AVAILABLE, 1
      value :NAME_AVAILABILITY_UNAVAILABLE, 2
      value :NAME_AVAILABILITY_INVALID, 3
      value :NAME_AVAILABILITY_PROFANE, 4
      value :NAME_AVAILABILITY_RESERVED, 5
    end
  end
end

module Aserto
  module Api
    module V1
      NameAvailability = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.NameAvailability").enummodule
    end
  end
end
