# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/policyref.proto

require 'google/protobuf'

require 'aserto/options/v1/ids_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/policyref.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.PolicyRef" do
      optional :id, :string, 1, json_name: "id"
      optional :name, :string, 2, json_name: "name"
      optional :source_url, :string, 3, json_name: "sourceUrl"
      optional :connection_id, :string, 4, json_name: "connectionId"
      optional :source_name, :string, 5, json_name: "sourceName"
      proto3_optional :decision_logging, :bool, 6, json_name: "decisionLogging"
      optional :registry_connection_id, :string, 7, json_name: "registryConnectionId"
      optional :registry_image, :string, 8, json_name: "registryImage"
      optional :registry_tag, :string, 9, json_name: "registryTag"
      optional :registry_org, :string, 10, json_name: "registryOrg"
    end
  end
end

module Aserto
  module Api
    module V1
      PolicyRef = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.PolicyRef").msgclass
    end
  end
end
