# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/policy_image.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/policy_image.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.PolicyImage" do
      optional :name, :string, 1, json_name: "name"
      optional :public, :bool, 2, json_name: "public"
    end
  end
end

module Aserto
  module Api
    module V1
      PolicyImage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.PolicyImage").msgclass
    end
  end
end
