# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/registry.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/registry.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.RegistryRepo" do
      optional :name, :string, 1, json_name: "name"
      optional :org, :string, 2, json_name: "org"
    end
    add_message "aserto.api.v1.RegistryRepoTag" do
      optional :name, :string, 1, json_name: "name"
      optional :digest, :string, 2, json_name: "digest"
      optional :size, :int64, 3, json_name: "size"
      optional :created_at, :message, 4, "google.protobuf.Timestamp", json_name: "createdAt"
      repeated :annotations, :message, 5, "aserto.api.v1.RegistryRepoAnnotation", json_name: "annotations"
    end
    add_message "aserto.api.v1.RegistryRepoAnnotation" do
      optional :key, :string, 1, json_name: "key"
      optional :value, :string, 2, json_name: "value"
    end
    add_message "aserto.api.v1.RegistryRepoDigest" do
      optional :digest, :string, 1, json_name: "digest"
      repeated :tags, :string, 2, json_name: "tags"
      optional :created_at, :message, 3, "google.protobuf.Timestamp", json_name: "createdAt"
    end
  end
end

module Aserto
  module Api
    module V1
      RegistryRepo = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.RegistryRepo").msgclass
      RegistryRepoTag = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.RegistryRepoTag").msgclass
      RegistryRepoAnnotation = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.RegistryRepoAnnotation").msgclass
      RegistryRepoDigest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.RegistryRepoDigest").msgclass
    end
  end
end
