# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/scc_org.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/scc_org.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.SccOrg" do
      optional :name, :string, 1, json_name: "name"
      optional :id, :string, 2, json_name: "id"
    end
  end
end

module Aserto
  module Api
    module V1
      SccOrg = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.SccOrg").msgclass
    end
  end
end
