# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aserto/api/v1/user.proto

require 'google/protobuf'

require 'google/protobuf/struct_pb'
require 'aserto/api/v1/metadata_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("aserto/api/v1/user.proto", :syntax => :proto3) do
    add_message "aserto.api.v1.User" do
      optional :id, :string, 1, json_name: "id"
      proto3_optional :enabled, :bool, 2, json_name: "enabled"
      optional :display_name, :string, 3, json_name: "displayName"
      optional :email, :string, 4, json_name: "email"
      optional :picture, :string, 5, json_name: "picture"
      map :identities, :string, :message, 6, "aserto.api.v1.IdentitySource"
      optional :attributes, :message, 7, "aserto.api.v1.AttrSet", json_name: "attributes"
      map :applications, :string, :message, 8, "aserto.api.v1.AttrSet"
      optional :metadata, :message, 9, "aserto.api.v1.Metadata", json_name: "metadata"
      optional :deleted, :bool, 10, json_name: "deleted"
    end
    add_message "aserto.api.v1.UserExt" do
      optional :id, :string, 1, json_name: "id"
      optional :attributes, :message, 7, "aserto.api.v1.AttrSet", json_name: "attributes"
      map :applications, :string, :message, 8, "aserto.api.v1.AttrSet"
    end
    add_message "aserto.api.v1.DeleteUser" do
      optional :id, :string, 1, json_name: "id"
    end
    add_message "aserto.api.v1.DeleteConnection" do
      optional :connection_id, :string, 1, json_name: "connectionId"
    end
    add_message "aserto.api.v1.AttrSet" do
      optional :properties, :message, 1, "google.protobuf.Struct", json_name: "properties"
      repeated :roles, :string, 2, json_name: "roles"
      repeated :permissions, :string, 4, json_name: "permissions"
    end
    add_message "aserto.api.v1.ApplExt" do
      map :applications, :string, :message, 1, "aserto.api.v1.AttrSet"
    end
    add_message "aserto.api.v1.IdentitySource" do
      optional :kind, :enum, 1, "aserto.api.v1.IdentityKind", json_name: "kind"
      optional :provider, :string, 2, json_name: "provider"
      optional :verified, :bool, 3, json_name: "verified"
      proto3_optional :connection_id, :string, 4, json_name: "connectionId"
      proto3_optional :case_insensitive, :bool, 5, json_name: "caseInsensitive"
    end
    add_message "aserto.api.v1.UserProcessStats" do
      optional :received, :int32, 1, json_name: "received"
      optional :created, :int32, 2, json_name: "created"
      optional :updated, :int32, 3, json_name: "updated"
      optional :deleted, :int32, 4, json_name: "deleted"
      optional :errors, :int32, 5, json_name: "errors"
    end
    add_enum "aserto.api.v1.IdentityKind" do
      value :IDENTITY_KIND_UNKNOWN, 0
      value :IDENTITY_KIND_PID, 1
      value :IDENTITY_KIND_EMAIL, 2
      value :IDENTITY_KIND_USERNAME, 3
      value :IDENTITY_KIND_DN, 4
      value :IDENTITY_KIND_PHONE, 5
      value :IDENTITY_KIND_EMPID, 6
    end
    add_enum "aserto.api.v1.AttrKind" do
      value :ATTR_KIND_UNKNOWN, 0
      value :ATTR_KIND_TITLE, 1
      value :ATTR_KIND_DEPARTMENT, 2
      value :ATTR_KIND_DIVSION, 3
      value :ATTR_KIND_COMPANY, 4
      value :ATTR_KIND_EMPLOYEE_ID, 5
      value :ATTR_KIND_EMPLOYEE_TYPE, 6
      value :ATTR_KIND_EMPLOYEE_NUMBER, 7
      value :ATTR_KIND_MANAGER, 8
      value :ATTR_KIND_FIRST_NAME, 9
      value :ATTR_KIND_INITIALS, 10
      value :ATTR_KIND_LAST_NAME, 11
      value :ATTR_KIND_COMMON_NAME, 12
    end
  end
end

module Aserto
  module Api
    module V1
      User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.User").msgclass
      UserExt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.UserExt").msgclass
      DeleteUser = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.DeleteUser").msgclass
      DeleteConnection = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.DeleteConnection").msgclass
      AttrSet = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.AttrSet").msgclass
      ApplExt = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.ApplExt").msgclass
      IdentitySource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.IdentitySource").msgclass
      UserProcessStats = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.UserProcessStats").msgclass
      IdentityKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.IdentityKind").enummodule
      AttrKind = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("aserto.api.v1.AttrKind").enummodule
    end
  end
end
