name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
      proto_sha:
  push:
    branches:
      - main
      - v*
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for PRs
  pull_request:

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  GO_VERSION: "1.17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Read Configuration
      uses: hashicorp/vault-action@v2.1.0
      id: vault
      with:
        url: ${{ env.VAULT_ADDR }}
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/github  "SSH_PRIVATE_KEY"     | SSH_PRIVATE_KEY;
          kv/data/buf.build "ASERTO_BUF_TOKEN"  | ASERTO_BUF_TOKEN;

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Setup caching
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          .ext
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', 'Depfile') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: |
          mkdir -p $HOME/.ssh
          umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts

          git config --global url."git@github.com:".insteadOf https://github.com/
          git config --global user.email "github-bot@aserto.com"
          git config --global user.name "Aserto Bot"

          eval `ssh-agent`
          ssh-add $HOME/.ssh/id_rsa

          go run mage.go deps

    - name: Clean generated code
      run: go run mage.go clean

    - name: Setup Buf Registry
      run: echo -e "machine buf.build\npassword ${ASERTO_BUF_TOKEN}" >> ~/.netrc

    - name: Generate
      run: go run mage.go generate

    - name: Commit changes
      if: github.event_name == 'workflow_dispatch'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: 'lib'
        push: origin HEAD:main

    - name: Build the gem
      run: go run mage.go build

  test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run rubocop
        run: bundle exec rubocop --parallel

      - name: run RSpec
        run: bundle exec rspec

  release:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    name: Release to rubygems
    steps:
      - name: Read Configuration
        uses: hashicorp/vault-action@v2.1.0
        id: vault
        with:
          url: ${{ env.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            kv/data/github  "SSH_PRIVATE_KEY"    | SSH_PRIVATE_KEY;
            kv/data/rubygems  "RUBYGEMS_API_KEY" | GEM_HOST_API_KEY;

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup caching
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            .ext
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', 'Depfile') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: |
            mkdir -p $HOME/.ssh
            umask 0077 && echo -e "${SSH_PRIVATE_KEY}" > $HOME/.ssh/id_rsa
            ssh-keyscan github.com >> $HOME/.ssh/known_hosts

            git config --global url."git@github.com:".insteadOf https://github.com/
            git config --global user.email "github-bot@aserto.com"
            git config --global user.name "Aserto Bot"

            eval `ssh-agent`
            ssh-add $HOME/.ssh/id_rsa

            go run mage.go deps

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Build and push the gem
        run: go run mage.go release

      - name: Bump to the next version
        run: go run mage.go bump patch

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Bump to next version'
          add: 'VERSION'
          push: origin HEAD:main
